### ISSUE TITLE
LogitechLed.dll文件不存在

### ISSUE THREAD

**Issue by 1246780072** [Weltolk/R3nzSkin_tool#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Weltolk** [comment]
On which League of Legends server are you using it?

**Comment by Weltolk** [comment]
Injection by replacing the LogitechLed.dll file is mainly for Chinese servers, because R3nzSkin's normal injection method does not work for Chinese servers (Chinese servers have Tencent's TP protection program)

If it is the League of Legends direct server, under normal circumstances you can directly use the injection provided by R3nzSkin

Just now I checked and searched the game folder of the League of Legends direct server, there is no LogitechLed.dll file, so this method may not work for the direct server

**Comment by 1246780072** [comment]
fine
